List<Map> events=[
  {
    "event_name":"sivan pojjai for sivan the event of the woroke resreed xcvbnm",
    "client_name":"siva rajna r",
    "client_mobile_number":"8248692839",
    "event_date":"15-04-2005",
    "event_start_at":"12:30 pm",
    "event_end_at":"12:30 pm",
    "event_status":"cancled",
    "event_description":"this the event of the woroke this the event of the woroke resreed xcvbnm",
    "payment_status":"fully paid",
    "payment_mode":"online",
    "payment_amount":"12345678",
    "total_amount":"34567890",
    "district":"madurai",

    "updated_by":"siva jeeva t",
    "updated_date":"15-04-2005",
    "updated_time":"12:30 pm",
    "feedback":"this is the feedback",
    "tips":"11233bddjdsfbf",
    "poojai":"qwrkbvccsdfghjkl",
    "abisegam":"qwertyuiopasdfghjkl",
    "helper":"wertyuiopasdfghjkl;",
    "poo":"qwertyuiop",
    "read":"qwertyuiopl,msdfghjkl",
    "prepare":"qwertyuiopsdfghjkmmm",
    "tips_shared":"qwertyuiopasdfghkl",
    "tips_given_to":"asdfghklxcvbnm,qwert",

    "image_url":"assets/image/WhatsApp Image 2025-04-17 at 12.40.40 AM.jpeg"
  },
  {
    "event_name":"something poojai event 1",
    "client_name":"siva rajna r",
    "client_mobile_number":"8248692839",
    "event_date":"15-04-2005",
    "event_start_at":"12:30 pm",
    "event_end_at":"12:30 pm",
    "event_status":"pending",
    "event_description":"this the event of the woroke",
    "payment_status":"fully paid",
    "payment_mode":"online",
    "payment_amount":"12345678",
    "total_amount":"34567890",
    "district":"madurai",

    "updated_by":"siva jeeva t",
    "updated_date":"15-04-2005",
    "updated_time":"12:30 pm",
    "feedback":"this is the feedback",
    "tips":"11233bddjdsfbf",
    "poojai":"qwrkbvccsdfghjkl",
    "abisegam":"qwertyuiopasdfghjkl",
    "helper":"wertyuiopasdfghjkl;",
    "poo":"qwertyuiop",
    "read":"qwertyuiopl,msdfghjkl",
    "prepare":"qwertyuiopsdfghjkmmm",
    "tips_shared":"qwertyuiopasdfghkl",
    "tips_given_to":"asdfghklxcvbnm,qwert",

    "image_url":"assets/image/WhatsApp Image 2025-04-17 at 12.40.40 AM.jpeg"
  },
  {
    "event_name":"something poojai event 2",
    "client_name":"siva rajna r",
    "client_mobile_number":"8248692839",
    "event_date":"15-04-2005",
    "event_start_at":"12:30 pm",
    "event_end_at":"12:30 pm",
    "event_status":"pending",
    "event_description":"this the event of the woroke",
    "payment_status":"fully paid",
    "payment_mode":"online",
    "payment_amount":"12345678",
    "total_amount":"34567890",
    "district":"madurai",

    "updated_by":"siva jeeva t",
    "updated_date":"15-04-2005",
    "updated_time":"12:30 pm",
    "feedback":"this is the feedback",
    "tips":"11233bddjdsfbf",
    "poojai":"qwrkbvccsdfghjkl",
    "abisegam":"qwertyuiopasdfghjkl",
    "helper":"wertyuiopasdfghjkl;",
    "poo":"qwertyuiop",
    "read":"qwertyuiopl,msdfghjkl",
    "prepare":"qwertyuiopsdfghjkmmm",
    "tips_shared":"qwertyuiopasdfghkl",
    "tips_given_to":"asdfghklxcvbnm,qwert",

    "image_url":"assets/image/nanmaitharuvar kovil.jpeg"
  },
  {
    "event_name":"something poojai event 3",
    "client_name":"siva rajna r",
    "client_mobile_number":"8248692839",
    "event_date":"15-04-2005",
    "event_start_at":"12:30 pm",
    "event_end_at":"12:30 pm",
    "event_status":"pending",
    "event_description":"this the event of the woroke",
    "payment_status":"fully paid",
    "payment_mode":"online",
    "payment_amount":"12345678",
    "total_amount":"34567890",
    "district":"madurai",

    "updated_by":"siva jeeva t",
    "updated_date":"15-04-2005",
    "updated_time":"12:30 pm",
    "feedback":"this is the feedback",
    "tips":"11233bddjdsfbf",
    "poojai":"qwrkbvccsdfghjkl",
    "abisegam":"qwertyuiopasdfghjkl",
    "helper":"wertyuiopasdfghjkl;",
    "poo":"qwertyuiop",
    "read":"qwertyuiopl,msdfghjkl",
    "prepare":"qwertyuiopsdfghjkmmm",
    "tips_shared":"qwertyuiopasdfghkl",
    "tips_given_to":"asdfghklxcvbnm,qwert",

    "image_url":""
  },
  {
    "event_name":"something poojai event 3",
    "client_name":"siva rajna r",
    "client_mobile_number":"8248692839",
    "event_date":"15-04-2005",
    "event_start_at":"12:30 pm",
    "event_end_at":"12:30 pm",
    "event_status":"finished",
    "event_description":"this the event of the woroke",
    "payment_status":"fully paid",
    "payment_mode":"online",
    "payment_amount":"12345678",
    "total_amount":"34567890",
    "district":"madurai",

    "updated_by":"siva jeeva t",
    "updated_date":"15-04-2005",
    "updated_time":"12:30 pm",
    "feedback":"this is the feedback",
    "tips":"11233bddjdsfbf",
    "poojai":"qwrkbvccsdfghjkl",
    "abisegam":"qwertyuiopasdfghjkl",
    "helper":"wertyuiopasdfghjkl;",
    "poo":"qwertyuiop",
    "read":"qwertyuiopl,msdfghjkl",
    "prepare":"qwertyuiopsdfghjkmmm",
    "tips_shared":"qwertyuiopasdfghkl",
    "tips_given_to":"asdfghklxcvbnm,qwert",

    "image_url":""
  },
  {
    "event_name":"something poojai event 3",
    "client_name":"siva rajna r",
    "client_mobile_number":"8248692839",
    "event_date":"15-04-2005",
    "event_start_at":"12:30 pm",
    "event_end_at":"12:30 pm",
    "event_status":"finished",
    "event_description":"this the event of the woroke",
    "payment_status":"fully paid",
    "payment_mode":"online",
    "payment_amount":"12345678",
    "total_amount":"34567890",
    "district":"madurai",

    "updated_by":"siva jeeva t",
    "updated_date":"15-04-2005",
    "updated_time":"12:30 pm",
    "feedback":"this is the feedback",
    "tips":"11233bddjdsfbf",
    "poojai":"qwrkbvccsqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqdfghjkl",
    "abisegam":"qwertyuiopasdfghjkl",
    "helper":"wertyuiopasdfghjkl;",
    "poo":"qwertyuiop",
    "read":"qwertyuiopl,msdfghjkl",
    "prepare":"qwertyuiopsdfghjkmmm",
    "tips_shared":"qwertyuiopasdfghkl",
    "tips_given_to":"asdfghklxcvbnm,qwert",

    "image_url":""
  }
];